# Generated by Django 5.1.15 on 2026-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='category',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Monthly budget cap for expense categories', max_digits=12, null=True),
        ),
    ]
