services:

  db:
    image: postgres:16
    container_name: postgresDB
    env_file:
      - ./db/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - finance-network

  worker:
    container_name: django
    command: bash -c "./wait-for-it.sh db:5432 -- && uv run python manage.py migrate && uv run python manage.py runserver 0.0.0.0:8000"
    build: ./backend
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG_DOCKER=True
    volumes:
      - "./backend:/usr/src/app:z"
      - /usr/src/app/.venv
    depends_on:
      - db
    networks:
      - finance-network
    ports:
      - 9090:8000

  web:
    container_name: react
    build: ./frontend
    volumes:
      - "./frontend:/usr/src/finance/app:z"
      - /usr/src/finance/node_modules
    env_file:
      - path: ./frontend/.env
        required: false
    ports:
      - 8080:5100
    stdin_open: true

volumes:
  postgres-data:

networks:
  finance-network:
