# Generated by Django 2.2.10 on 2020-04-15 08:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('expected', models.DecimalField(decimal_places=4, max_digits=12)),
                ('must_show', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finance.Source')),
                ('bank', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finance.Source')),
                ('cut', models.IntegerField()),
                ('pay', models.IntegerField()),
                ('bank', models.CharField(max_length=120)),
                ('credit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('used', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='finance.Source')),
                ('balance', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('account_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_from', to='finance.Source')),
                ('account_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_to', to='finance.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('is_payed', models.BooleanField(default=1)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Source')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Category')),
            ],
        ),
    ]
