# Generated by Django 2.2.10 on 2020-06-04 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.Account'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.Category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_origin', to='finance.Account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='account_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_destiny', to='finance.Account'),
        ),
    ]
